include_guard()
include(cmake_test/detail_/debug)
include(cmake_test/detail_/print_status)
include(cmake_test/detail_/utilities)

function(_ct_start_section _ss_handle _ss_name)
    _ct_parse_debug("Parsing section: ${_ss_name}")
    _ct_append_target(${_ss_handle} CT_TEST_NAME "${_ss_name}")
endfunction()

function(_ct_end_section _es_handle _es_prefix)
    _ct_parse_debug("Finished section at depth ${_ct_sec_depth}")
    _ct_write_and_run_contents(${_es_prefix} ${_es_handle})

    _ct_get_value(_es_names ${_es_handle} CT_TEST_NAME)
    list(LENGTH _es_names _es_depth)
    math(EXPR _es_m1 "${_es_depth} - 1")
    foreach(_es_prop CT_TEST_NAME CT_SHOULD_PASS CT_PRINTS)
        _ct_get_value(_es_value ${_es_handle} ${_es_prop})
        list(LENGTH _es_value _es_n)
        if("${_es_n}" STREQUAL "${_es_depth}")
            list(REMOVE_AT _es_value ${_es_m1})
            _ct_set_value(${_es_handle} ${_es_prop} "${_es_value}")
        endif()
    endforeach()
endfunction()
