include_guard()

function(_ct_parse_assert _pa_handle _pa_line)
    _ct_parse_debug("Assert: ${_pa_line}")
    _ct_lc_find(_pa_is_print "ct_assert_prints" "${_pa_line}")
    _ct_lc_find(_pa_is_equal "ct_assert_equal" "${_pa_line}")
    _ct_lc_find(_pa_not_def  "ct_assert_not_defined" "${_pa_line}")
    if(_pa_is_print)
        string(REGEX MATCH "\\(\\s*\"(.*)\"\\s*\\)" _pa_match "${_pa_line}")
        _ct_update_target(${_pa_handle} CT_PRINTS "${CMAKE_MATCH_1}")
    elseif(_pa_is_equal)
        message("Equal assert: ${_pa_line}")
    elseif(_pa_not_def)
        message("Not defined: ${_pa_line}")
    else()
        message(FATAL_ERROR "Unrecognized assert")
    endif()
endfunction()
