include_guard()

function(_ct_variable_is_set _vis_var)
    cmake_policy(SET CMP0054 NEW)
    if("${${_vis_var}}" STREQUAL "")
        message(FATAL_ERROR "${ARGN}")
    endif()
endfunction()

macro(_ct_return _r_var)
    set(${${_r_var}} "${${${_r_var}}}" PARENT_SCOPE)
endmacro()

function(_ct_lc_find _lf_found _lf_str _lf_line)
    string(FIND "${_lf_line}" "${_lf_str}" _lf_pos)
    set(${_lf_found} TRUE PARENT_SCOPE)
    if("${_lf_pos}" STREQUAL "-1")
        set(${_lf_found} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_ct_sanitize_name _sn_new_name _sn_old_name)
    string(TOLOWER "${_sn_old_name}" _sn_old_name)
    string(REPLACE " " "_" ${_sn_new_name} "${_sn_old_name}")
    set(${_sn_new_name} "${${_sn_new_name}}" PARENT_SCOPE)
endfunction()

function(_ct_get_value _gv_value _gv_handle _gv_prop)
    set(_gv_name "${_gv_handle}_${_gv_prop}")
    get_property(${_gv_value} GLOBAL PROPERTY ${_gv_name})
    set(${_gv_value} "${${_gv_value}}" PARENT_SCOPE)
endfunction()

function(_ct_set_value _sv_handle _sv_prop _sv_value)
    set(_sv_name "${_sv_handle}_${_sv_prop}")
    set_property(GLOBAL PROPERTY "${_sv_name}" "${_sv_value}")
endfunction()

function(_ct_append_target _at_handle _at_prop _at_value)
    _ct_get_value(_at_temp ${_at_handle} ${_at_prop})
    list(APPEND _at_temp "${_at_value}")
    _ct_set_value(${_at_handle} ${_at_prop} ${_at_temp})
endfunction()

function(_ct_update_target _ut_handle _ut_prop _ut_value)
    _ct_get_value(_ut_names ${_ut_handle} CT_TEST_NAME)
    _ct_get_value(_ut_name ${_ut_handle} ${_ut_prop})
    list(LENGTH _ut_names _ut_depth)
    list(LENGTH _ut_name _ut_depth2)
    if("${_ut_depth}" STREQUAL "${_ut_depth2}") #Just append to values
        if("${_ut_depth}" STREQUAL "0")
            set(_ut_name "${_ut_value}")
        else()
            list(GET _ut_name -1 _ut_elem)
            set(_ut_elem "${_ut_elem}${_ut_value}")
            list(INSERT _ut_name -1 "${_ut_elem}")
        endif()
    elseif("${_ut_depth}" GREATER "${_ut_depth2}")
        math(EXPR _ut_m1 "${_ut_depth} - 1")
        while("${_ut_depth2}" LESS "${_ut_m1}")
            list(APPEND _ut_name "")
        endwhile()
        list(APPEND _ut_name "${_ut_value}")
    else()
        message(FATAL_ERROR "Didn't clean target up right")
    endif()

    _ct_set_value(${_ut_handle} ${_ut_prop} "${_ut_name}")
endfunction()
