include(cmake_test/detail_/test_state/test_state)

#test_state(CTOR state "TestState Class")
#test_state(PRINT ${state})
#message("======================================================================")
#test_state(ADD_CONTENT ${state} "Hello World")
#test_state(MUST_PRINT ${state} "Hello World")
#test_state(PRINT ${state})
#message("======================================================================")
#test_state(ADD_SECTION ${state} "Section 1")
#test_state(ADD_CONTENT ${state} "Good bye world")
#test_state(MUST_PRINT ${state} "Good bye world")
#test_state(PRINT ${state})
#message("======================================================================")
#
#test_state(END_SECTION ${state})
#test_state(PRINT ${state})
