#This is the main workflow to autogenerate documentation

name: autodocs
on:
  push:
    branches:
      - master
jobs:
  autodocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build Docs
        run: |
          python3 -m venv virt_env
          source virt_env/bin/activate
          pip3 install wheel
          cd docs
          pip3 install -r requirements.txt
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
